# Generated by Django 4.2.5 on 2023-09-16 06:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_customuser_dark_theme"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="high_score",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
