# Generated by Django 4.2.5 on 2023-09-16 09:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_customuser_high_score"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="age",
        ),
    ]
